apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "auth.fullname" . }}
  labels:
    {{- include "auth.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "auth.labels" . | indent 8 }}
    spec:
      initContainers:
      {{- include "auth.customer.initcontainer" . | indent 6 }}
      containers:
      - name: {{ .Chart.Name | quote }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.managementPort }}
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.managementPort }}
          initialDelaySeconds: 35
          periodSeconds: 20
          failureThreshold: 6
        env:
        {{- include "auth.environmentvariables" . | indent 8 }}
        {{- include "auth.customer.environmentvariables" . | indent 8 }}
        {{- include "auth.hs256key.environmentvariables" . | indent 8 }}
        resources:
{{ toYaml .Values.resources | indent 10 }}